mmm_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  base_to_lwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_lwheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_to_rwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_to_rwheel
    pid: {p: 100.0, i: 0.01, d: 10.0}